version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:80
    volumes:
      - .:/var/www/html
    depends_on:
      - db
      # - cron
    networks:
      - app-network

  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dbname
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
    networks:
      - app-network

  cron:
    build:
      context: .
      dockerfile: Dockerfile-Cron
    volumes:
      - .:/var/www/html
      - ./log/cron:/var/log/cron
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
    driver: local