FROM php:8.2-fpm-alpine

RUN docker-php-ext-install pdo pdo_mysql

COPY . /var/www/html/

WORKDIR /var/www/html/

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN composer install

COPY crontab /etc/crontabs/root

RUN mkdir /var/log/cron

CMD ["crond", "-f"]