version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:80
    volumes:
      - .:/var/www/html
    depends_on:
      - db
      - cron

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: currenciesDB
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234

  cron:
    build:
      context: .
      dockerfile: Dockerfile.cron
    volumes:
      - .:/var/www/html