FROM php:8.2-fpm-alpine

RUN docker-php-ext-install pdo pdo_mysql

# COPY crontab /etc/crontabs/root
# RUN mkdir /var/log/cron

# CMD ["crond", "-f"]

# RUN apk —no-cache add mysql-client

# RUN docker-php-ext-install pdo pdo_mysql
COPY . /var/www/html/

WORKDIR /var/www/html/

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Установка зависимостей проекта
RUN composer install

COPY crontab /etc/crontabs/root

RUN mkdir /var/log/cron

# COPY --from=composer /usr/bin/composer /usr/bin/composer

# WORKDIR /var/www/html
# COPY composer.json composer.lock ./
# RUN composer install --prefer-dist --no-scripts --no-autoloader

# COPY . /var/www/html

# RUN composer dump-autoload --no-scripts --no-dev --optimize

CMD ["crond", "-f"]